# Generated by Django 5.1.7 on 2025-04-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_remove_faultcase_images_remove_faultcase_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultcase',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Technician or Manager who reported the fault', limit_choices_to={'role__in': ['TECH', 'MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_faults', to=settings.AUTH_USER_MODEL),
        ),
    ]
