# Generated by Django 5.1.7 on 2025-03-29 16:03

import django.db.models.deletion
import machinery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name (e.g. Main-Campus, Floor-2)', max_length=100, unique=True, validators=[machinery.models.validate_collection_name])),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the machine', max_length=255)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAULT', 'Fault')], default='OK', help_text='Current status of the machine', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(help_text='Technicians and Repairers assigned to this machine', limit_choices_to={'role__in': ['TECH', 'REPAIR']}, related_name='assigned_machines', to=settings.AUTH_USER_MODEL)),
                ('collections', models.ManyToManyField(help_text='User-defined tags like location or type', related_name='machines', to='machinery.collection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Free-form warning message', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(help_text='User who added the warning', on_delete=django.db.models.deletion.PROTECT, related_name='added_warnings', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(help_text='Machine associated with this warning', on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='machinery.machine')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('machine', 'message')},
            },
        ),
    ]
