# Generated by Django 5.1.7 on 2025-03-29 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='assigned_users',
            field=models.ManyToManyField(help_text='Technicians and Repairers assigned to this machine', limit_choices_to={'role__in': ['TECH', 'REPAIR', 'MANAGER']}, related_name='assigned_machines', to=settings.AUTH_USER_MODEL),
        ),
    ]
