# Generated by Django 5.1.7 on 2025-04-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_alter_machine_assigned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added the warning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_warnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
